# Generated by Django 2.2 on 2021-08-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210823_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
